apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-dump-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: java-dump-local
  hostPath:
    path: /var/log/java-dump
    type: DirectoryOrCreate