apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-homework.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "platform-homework.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "platform-homework.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
    {{- if .Values.jvmExporter.enabled }}
    - name: jmx
      port: 9010
      targetPort: 9010
    {{- end }}
  type: {{ .Values.service.type }}