name: CI for Platform Homework Java App

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: ghcr.io/tisamwilliam/spring-hello-problem
  IMAGE_TAG: 1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: docker/spring-hello-problem

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
        working-directory: docker/spring-hello-problem

      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

  # helm-validate:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Helm
  #       uses: azure/setup-helm@v3
  #       with:
  #         version: v3.13.0

  #     - name: Helm lint
  #       run: helm lint ./charts/java-app

  #     - name: Helm template dry-run
  #       run: |
  #         helm template test ./charts/java-app \
  #           --set image.repository=${{ env.IMAGE_NAME }} \
  #           --set image.tag=latest
